from selenium.webdriver.common.by import By


class MainPageLocators:
    FINDER_ACCESSORIES_LINK = (By.XPATH, '//*[contains(text(), "FIND YOUR NEXT ACCESSORY")]')
    ACCESSORIES_BUTTON = (By.CSS_SELECTOR, '.sEvIw')
    STORE_LINK = (By.CSS_SELECTOR, '.byqvMJ')
    HIAB_SHOP_LNK = (By.CSS_SELECTOR, '.bMedPF>:nth-child(1)')
    HIAB_LOGO_LNK = (By.CSS_SELECTOR, '.l-s-header__svg-logo')
    SEARCH_BY_FIELD = (By.CSS_SELECTOR, '#search-main')
    LANGUAGE_BUTTON = (By.CSS_SELECTOR, '.hhCVAr')
    CHOOSE_LANGUAGE_IT = (By.XPATH, '//a[@href="/it"]') #.gQbTuY>div>div>:nth-child(3)>:nth-child(11)
    # CHOOSE_LANGUAGE_DE = (By.XPATH, '//a[contains(text(), "Germany")]')
    IT_ELEMENT = (By.CSS_SELECTOR, '.hhCVAr')
    SEARCH_BUTTON = (By.CSS_SELECTOR, '.jwaUmM')
    SUBMIT_BUTTON = (By.XPATH, '//button[@type="submit"]')
    DOWNLOADED_SEARCH_FIELD = (By.ID, 'nav-search')
    RESULTS_IN_ALL_TAB = (By.XPATH, '.dGLnrg > strong:nth-child(1)')
    ABOUT_US_PAGE = (By.CSS_SELECTOR, '.bgWvqG>div>ul>li:nth-child(1)')
    ABOUT_US_BREADCRUMB = (By.CSS_SELECTOR,'.fWZFwD>ul>li:nth-child(2)')
    SUSTAINABILITY_PAGE = (By.CSS_SELECTOR, '.bgWvqG>div>ul>li:nth-child(2)')
    SUSTAINABILITY_BREADCRUMB = (By.CSS_SELECTOR, '.fWZFwD>ul>li:nth-child(3)')
    CAREERS_PAGE = (By.CSS_SELECTOR, '.bgWvqG>div>ul>li:nth-child(3)')
    CAREERS_BREADCRUMB = (By.CSS_SELECTOR, '.fWZFwD>ul>li:nth-child(2)')
    MEDIA_PAGE = (By.CSS_SELECTOR, '.bgWvqG>div>ul>li:nth-child(4)')
    MEDIA_BREADCRUMB = (By.CSS_SELECTOR, '.fWZFwD>ul>li:nth-child(2)')
    CLUB_SHOP_PAGE = (By.CSS_SELECTOR, '.bgWvqG>div>ul>li:nth-child(5)')
    CUSTOMER_BUTTON = (By.CSS_SELECTOR, '.vex-first')
    HICONNECT_FORM = (By.CSS_SELECTOR, '.vex-dialog-form')
    HICONNECT_PORTAL_PAGE = (By.XPATH, '//a[@href="https://hiconnect.hiab.com/app"]')
    HICONNECT_DESIRED_URL = ('https://hiconnect.hiab.com/app')
    HICONNECT_LOGIN_BUTTON = (By.CSS_SELECTOR, '.login__input')
    CONTACT_MEGA_MENU = (By.CSS_SELECTOR, '.dNZTyz>li:nth-child(5)')
    # CONTACT_US_BUTTON = (By.XPATH, '//a[@href="/en/contacts/corporate/hiab-corporate"]')
    FIND_A_DEALER = (By.CSS_SELECTOR, '.kMAVwy')
    OUR_BRANDS = (By.CSS_SELECTOR, '.dJmdQu')
